export const universities = [
  {
    id: 1,
    name: "Sorbonne Université",
    location: "Paris",
    logo: "🏛️",
    specialties: ["Lettres", "Sciences", "Médecine", "Ingénierie"],
  },
  {
    id: 2,
    name: "Sciences Po Paris",
    location: "Paris",
    logo: "🎓",
    specialties: ["Sciences Politiques", "Relations Internationales", "Économie", "Droit"],
  },
  {
    id: 3,
    name: "HEC Paris",
    location: "Jouy-en-Josas",
    logo: "💼",
    specialties: ["Management", "Finance", "Marketing", "Entrepreneuriat"],
  },
  {
    id: 4,
    name: "École Polytechnique",
    location: "Palaiseau",
    logo: "🔬",
    specialties: ["Ingénierie", "Mathématiques", "Physique", "Informatique"],
  },
  {
    id: 5,
    name: "ENS Paris",
    location: "Paris",
    logo: "📚",
    specialties: ["Lettres", "Sciences", "Philosophie", "Histoire"],
  },
  {
    id: 6,
    name: "Université Paris-Dauphine",
    location: "Paris",
    logo: "📊",
    specialties: ["Économie", "Gestion", "Mathématiques", "Informatique"],
  },
  {
    id: 7,
    name: "ESSEC Business School",
    location: "Cergy",
    logo: "🏢",
    specialties: ["Management", "Finance", "Marketing", "Luxe"],
  },
]

export const specialties = [
  'Informatique',
  'Mathematiques',
  'Physique',
  'Chimie',
  'Biologie',
  'Geologie',
  'Sciences de la Terre et de lUnivers',
  'Genie civil',
  'Genie mecanique',
  'Genie electrique',
  'Genie electronique',
  'Genie des procedes',
  'Genie industriel',
  'Genie biomedical',
  'Genie climatique',
  'Genie minier',
  'Genie petrolier',
  'Genie maritime',
  'Genie de leau',
  'Aeronautique',
  'Electromecanique',
  'Energies renouvelables',
  'Hydraulique',
  'Productique',
  'Telecommunications',
  'Medecine',
  'Pharmacie',
  'Chirurgie dentaire',
  'Sciences infirmieres',
  'Biologie medicale',
  'Sciences economiques',
  'Sciences de gestion',
  'Comptabilite',
  'Finance',
  'Marketing',
  'Commerce international',
  'Ressources humaines',
  'Droit prive',
  'Droit public',
  'Sciences politiques',
  'Relations internationales',
  'Langue et litterature arabe',
  'Langue et litterature francaise',
  'Langue et litterature anglaise',
  'Langues etrangeres appliquees',
  'Traduction',
  'Psychologie',
  'Sociologie',
  'Philosophie',
  'Histoire',
  'Geographie',
  'Anthropologie',
  'Arts plastiques',
  'Musique',
  'Theatre',
  'Cinema',
  'Patrimoine culturel',
  'Environnement',
  'Hygiene et securite industrielle',
  'Gestion des ressources naturelles'
]

export const bacTypes = [
  'sciences experimentales',
  'mathematiques',
  'technique mathematique',
  'gestion et economie',
  'lettres et philosophie',
  'langues etrangeres',
  'autre',
  'unknown',
]
